import { type NextPage } from "next";
import Head from "next/head";




const Page: NextPage = () => {

 

  


  

  return (
    <>
      <Head>
        <title>sonatrach</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" w-full min-h-screen bg-gray-50 flex justify-center items-center ">
        
        <div className="w-[500px] h-[400px] bg-white shadow-xl">
          <h1>check your email box to see the confirmation link</h1>
        </div>
    
      </main>
    </>
  );
};

export default Page;