import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Select from 'react-select';
import { Header } from "~/components/header/Header";
import { ControllingSidebar } from "~/components/sideBars/ControllingSidebar";
import { Form } from "~/components/used/Form";
import { FormContainer } from "~/components/used/FormContainer";
import { Input } from "~/components/used/Input";
import { TextField } from "~/components/used/TextField";
import { OPTIONS } from "~/types/static/STATICDATA";

const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
       <ControllingSidebar isOpen={isOpen} setIsOpen={setIsOpen} />
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[5rem]"}`}>
      
      <Form  >
  <div className="bg-white px-4 py-5 sm:p-6">
     <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
      

      <Input
                isLoading={false}
                lable="Title"
                onChange={(e) => console.log(e)}
                value={""}
       />
      <Input
                isLoading={false}
                lable="Date prepared"
                onChange={(e) => console.log(e)}
                value={""}
       />
      <Input
                isLoading={false}
                lable="Person requsting change"
                onChange={(e) => console.log(e)}
                value={""}
       />
       <Input
                isLoading={false}
                lable="Change number"
                onChange={(e) => console.log(e)}
                value={""}
        />
      <TextField
                isLoading={false}
                lable="Detailed Description of Proposed change"
                onChange={(e) => console.log(e)}
                value={""}

       />
        <TextField
                isLoading={false}
                lable="Justification for Proposed change"
                onChange={(e) => console.log(e)}
                value={""}

       />
       
            <div className="col-span-12 ">
                 <h2>impacts of change </h2>
            </div>
            <div className='col-span-6 flex justify-center flex-col items-start '>
                   <label  className="block text-sm font-medium leading-6 text-gray-900">
                                     Scope
                   </label>
                  <Select
                       
                          onChange={(e) => console.log(e)}  
                          name="scope"
                          options={OPTIONS}
                          className="basic-multi-select w-full"
                          classNamePrefix="select"/>
             </div>
             <TextField
                          isLoading={false}
                          lable="Description on impact of scope "
                          onChange={(e) => console.log(e)}
                          value={""}
             />

             <div className='col-span-6 flex justify-center flex-col items-start '>
                   <label  className="block text-sm font-medium leading-6 text-gray-900">
                                     grade
                   </label>
                  <Select
                       
                          onChange={(e) => console.log(e)}  
                          name="scope"
                          options={OPTIONS}
                          className="basic-multi-select w-full"
                          classNamePrefix="select"/>
              </div>
             <TextField
                          isLoading={false}
                          lable="Description on impact of grade "
                          onChange={(e) => console.log(e)}
                          value={""}
              />
               <div className='col-span-6 flex justify-center flex-col items-start '>
                   <label  className="block text-sm font-medium leading-6 text-gray-900">
                                    Requiriremts
                   </label>
                  <Select
                       
                          onChange={(e) => console.log(e)}  
                          name="scope"
                          options={OPTIONS}
                          className="basic-multi-select w-full"
                          classNamePrefix="select"/>
               </div>
              <TextField
                          isLoading={false}
                          lable="Description on impact of Requiriremts "
                          onChange={(e) => console.log(e)}
                          value={""}
               />

             <div className='col-span-6 flex justify-center flex-col items-start '>
                   <label  className="block text-sm font-medium leading-6 text-gray-900">
                                    Cost
                   </label>
                  <Select
                       
                          onChange={(e) => console.log(e)}  
                          name="scope"
                          options={OPTIONS}
                          className="basic-multi-select w-full"
                          classNamePrefix="select"/>
             </div>
              <TextField
                          isLoading={false}
                          lable="Description on impact of Cost "
                          onChange={(e) => console.log(e)}
                          value={""}
               />
             <div className='col-span-6 flex justify-center flex-col items-start '>
                   <label  className="block text-sm font-medium leading-6 text-gray-900">
                                    Schedule
                   </label>
                  <Select
                       
                          onChange={(e) => console.log(e)}  
                          name="scope"
                          options={OPTIONS}
                          className="basic-multi-select w-full"
                          classNamePrefix="select"/>
             </div>
              <TextField
                          isLoading={false}
                          lable="Description on impact of Schedule "
                          onChange={(e) => console.log(e)}
                          value={""}
               />
               <div className='col-span-6 flex justify-center flex-col items-start '>
                   <label  className="block text-sm font-medium leading-6 text-gray-900">
                                    Stakholder Impact
                   </label>
                  <Select
                       
                          onChange={(e) => console.log(e)}  
                          name="scope"
                          options={OPTIONS}
                          className="basic-multi-select w-full"
                          classNamePrefix="select"/>
             </div>
              <TextField
                          isLoading={false}
                          lable="Description  "
                          onChange={(e) => console.log(e)}
                          value={""}
               />
              <TextField
                          isLoading={false}
                          lable="Comments "
                          onChange={(e) => console.log(e)}
                          value={""}
                       
              />    
               <TextField
                          isLoading={false}
                          lable="Justification "
                          onChange={(e) => console.log(e)}
                          value={""}
                          
              />       
           
   


      </div>
  </div>
   
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;