import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Select from "react-select";
import { Header } from "~/components/common/Header";
import { ControllingSidebar } from "~/components/sideBars/ControllingSidebar";
import { AbdullahTable } from "~/components/ui/used/AbdullahTable";
import { Form } from "~/components/ui/used/Form";
import { FormContainer } from "~/components/ui/used/FormContainer";
import { FormHead } from "~/components/ui/used/FormHead";
import { TextField } from "~/components/ui/used/TextField";
import { STAKHOLDER_TYPES } from "~/types/static/STATICDATA";


const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
       <ControllingSidebar isOpen={isOpen} setIsOpen={setIsOpen} />
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[5rem]"}`}>
 
      <Form  >
      <div className="bg-white px-4 py-5 sm:p-6">
      <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
     
      <div className='col-span-6 '>
                  <label  className="block text-sm font-medium leading-6 text-gray-900">
                       Area Audited
                  </label>
                  <Select
                        onChange={(e) => console.log(e)}
                        name="stakholders_types"
                        options={STAKHOLDER_TYPES}
                        className="basic-multi-select"
                        classNamePrefix="select"
                    />
      </div> 
      <TextField
        lable="Good Practices to Share"
        onChange={(e) => console.log(e)}
        isLoading={false}
        value={""}
      />
      <TextField
        lable="Areas for Improvement"
        onChange={(e) => console.log(e)}
        isLoading={false}
        value={""}
      />

       
         <TextField
        lable="Comments"
        onChange={(e) => console.log(e)}
        isLoading={false}
        value={""}
      />
       <div className="col-span-6 lg:col-span-12">
        <AbdullahTable
        isLoading={false}
        
        title="Deficiencies or Defects"
        description="
         
         "
        Action ={false}
        headers={["ID" , "Defect" , "Action" , "Responsible Party" , "Due Date"]}
        body={[]}
    // PlusButton={<PlusButtonIssueManagment  />}
        />
        </div>
        </div>
      </div>
   
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;