import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Header } from "~/components/header/Header";
import { CloseSideBar } from "~/components/sideBars/CloseSideBar";
import { Form } from "~/components/used/Form";
import { FormContainer } from "~/components/used/FormContainer";
import { RowGridText } from "~/components/typography/RowGridText";
import { TextField } from "~/components/used/TextField";

const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
       <CloseSideBar isOpen={isOpen} setIsOpen={setIsOpen}/>
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[5rem]"}`}>
     
      <Form  >
      <div className="bg-white px-4 py-5 sm:p-6">
      <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
         
          
            <RowGridText text="Résumé des performances" />
            <RowGridText text="La clôture de projet est la phase finale où toutes les activités, les livrables et les objectifs sont terminés, et le projet est officiellement clôturé, visant à valider le succès du projet et faciliter la transition vers les opérations en cours ou les projets ultérieurs" small />

            {/* this is a row */}
            <TextField
                isLoading={false}
                lable=" Objectifs du projet (Portée)"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Critères de réalisation de la portée du projet"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Les objectifs de la portée ont été atteints."
                onChange={(e) => console.log(e)}
                value={""}
            />
            {/* this is another row  */}
            <TextField
                isLoading={false}
                lable="Objectifs de qualité du projet"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Critères de réalisation de la qualité"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Comment la qualité a été atteinte"
                onChange={(e) => console.log(e)}
                value={""}
            />
              {/* this is another row  */}
              <TextField
                isLoading={false}
                lable="Objectifs de temps du projet"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Critères de réalisation des délais"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Comment les objectifs de délais ont été atteints"
                onChange={(e) => console.log(e)}
                value={""}
            />
              {/* this is another row  */}
              <TextField
                isLoading={false}
                lable="Objectifs de coût du projet"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Critères de réalisation des coûts"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Comment les objectifs de coûts ont été atteints"
                onChange={(e) => console.log(e)}
                value={""}
            />
          
        </div>
      </div>
   
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;