import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Header } from "~/components/header/Header";
import { CloseSideBar } from "~/components/sideBars/CloseSideBar";
import { AbdullahTable } from "~/components/used/AbdullahTable";
import { Form } from "~/components/used/Form";
import { FormContainer } from "~/components/used/FormContainer";
import { FormHead } from "~/components/used/FormHead";
import { RowGridText } from "~/components/typography/RowGridText";
import { TextField } from "~/components/used/TextField";

const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
       <CloseSideBar isOpen={isOpen} setIsOpen={setIsOpen}/>
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[5rem]"}`}>
     
      <Form  >
      <div className="bg-white px-4 py-5 sm:p-6">
      <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
         
          
            <RowGridText text="Performance Summary" />
            {/* this is a row */}
            <TextField
                isLoading={false}
                lable="Scope Project Objectives"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Scope Completion Criteria"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Scope How Met"
                onChange={(e) => console.log(e)}
                value={""}
            />
            {/* this is another row  */}
            <TextField
                isLoading={false}
                lable="Quality Project Objectives"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Quality Completion Criteria"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Quality How Met"
                onChange={(e) => console.log(e)}
                value={""}
            />
              {/* this is another row  */}
              <TextField
                isLoading={false}
                lable="Time Project Objectives"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Time Completion Criteria"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Time How Met"
                onChange={(e) => console.log(e)}
                value={""}
            />
              {/* this is another row  */}
              <TextField
                isLoading={false}
                lable="Cost Project Objectives"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Cost Completion Criteria"
                onChange={(e) => console.log(e)}
                value={""}
            />
             <TextField
                isLoading={false}
                lable="Cost How Met"
                onChange={(e) => console.log(e)}
                value={""}
            />
          
        </div>
      </div>
   
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;