/* eslint-disable react/no-unescaped-entities */
import { Container } from '~/components/ui/used/Container'
import React from 'react'
import { Input } from '~/components/ui/used/Input'
import { AbdullahButton , buttonVariants } from '~/components/ui/buildingBlocks/AbdullahButton'
import { useState } from 'react'
import { api } from '~/utils/api'
import { toast } from 'react-toastify'
import {v4 as uuidV4} from "uuid"
import { getUserMetadata, setoreProjectMetaData } from '~/lib/MetaData'
import Head from 'next/head'
import { Header } from '~/components/common/Header'



type Props ={
  refetch : () => Promise<any>
}

 const Page = ({refetch} : Props) => {


  

  const {mutate , isLoading} = api.ProjectRouter.createProject.useMutation({
    onSuccess : async ({project_id}) => {
      toast(" the project started successfully ",{
        className:" !text-white !bg-blue-500",
        hideProgressBar: true,
       })
       
       setoreProjectMetaData({project_id })
      await  refetch()
    },
    onError : () => {
      toast(" error starting the project",{
        className:" !text-white !bg-blue-500",
        hideProgressBar: true,
       })
    }
  })

  const [data , setData ] = useState<string>("")

  const handleClick =  () => {

    const id:string  = uuidV4()
    mutate({
      id,
      user_id : getUserMetadata()
    })
  }






  return (
    <>
          <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  justify-center items-center flex w-full bg-gray-50 ">
      <Container className='flex flex-col items-center p-8 pt-12 bg-gray-50 '>
        <div className='w-[700px] h-[70px] flex flex-col justify-center gap-y-4 '>
            <h1 className='text-xl font-semibold text-gray-900 '>Change and manage your password</h1>
            <p className='text-lg  text-gray-400 '>Password settings</p>
        </div>
        <div className=' w-[700px] my-4 flex flex-col h-[250px] bg-white p-6 gap-y-4 '>
        <Input
        lable='enter your email'
        onChange={(e) =>setData(e.target.value)}
        value={data}

        />
        <Input
        lable='enter your old password'
        onChange={(e) =>setData(e.target.value)}
        value={data}

        />
          <Input
        lable='enter your new password'
        onChange={(e) =>setData(e.target.value)}
        value={data}

        />
        <div className='w-full h-[70px] flex justify-start items-center my-2'>
      
       <AbdullahButton
       onClick={handleClick}
       isLoading={isLoading}
       className={`${buttonVariants({variant:"primary" })} `}
        >
          confirme and change
       </AbdullahButton>
        </div>
        </div>
    </Container>
      </main>
    </>
   
  )
}


export default Page