import { NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/header/Header";
import { getProjectMetaData, getUserMetadata, deteProjectMetaData } from "~/lib/MetaData";
import { AbdullahButton } from "~/components/used/AbdullahButton";
import { Button } from "@tremor/react";
import { api } from "~/utils/api";
import toast from "react-hot-toast";
import { CookieSettings } from "~/components/common/cookies-settings";

const Page: NextPage = () => {
  const projectMutation = api.projectRouter.delete_project.useMutation({
    onSuccess() {
      deteProjectMetaData();
      toast.success("Your project has been deleted successfully");
    },
    onError() {
      toast.error("Something went wrong");
    },
  });

  const deleteMyProject = () => {
    projectMutation.mutate({
      project_id: getProjectMetaData(),
    });
  };

  return (
    <>
      <Head>
        <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className="custopn-page-height   w-full bg-gray-50 py-8">
        <div className="w-full max-w-6xl min-h-[500px] mx-auto  flex p-4 pt-12 mt-8 flex-col  h-fit bg-white rounded-lg shadow-lg">


        <CookieSettings />

          <div className="w-[95%] my-4 p-4 mx-auto min-h-[200px]  rounded-lg border flex flex-col">
         
            <div className="w-full h-[140px] flex flex-col justify-start">
              <h4 className="text-xl font-semibold text-gray-900 font-sans text-start">Delete My Project</h4>
              <p className="text-md font-sans text-gray-400 text-start">
                By selecting this option, you are about to initiate the deletion of your project from the Project Management Platform. It is essential to understand that this action is irreversible, meaning that once completed, it cannot be undone. Therefore, we strongly urge you to exercise caution and make sure this is the intended course of action.
              </p>
            </div>
            <div className="h-[60px] w-full flex justify-end items-center p-4">
              <AbdullahButton onClick={deleteMyProject} isLoading={projectMutation.isLoading} className="bg-red-500 text-white font-semibold">
                Delete my Project
              </AbdullahButton>
            </div>
          </div>

          <div className="w-[95%] my-4 p-4 mx-auto h-[200px] rounded-lg border flex flex-col">
            <div className="w-full h-[140px] flex flex-col justify-start">
              <h4 className="text-xl font-semibold text-gray-900 font-sans text-start">Delete Personal Account</h4>
              <p className="text-md font-sans text-gray-400 text-start">
                ProjectFlow values the privacy and control of our users' data. We provide this option to give you complete control over your account and its contents. By removing your Personal Account, all information, files, and any other data associated with your account will be permanently deleted from our servers. This includes any projects, documents, settings, and user preferences you have customized during your time on the platform.
              </p>
            </div>
            <div className="h-[60px] w-full flex justify-end items-center p-4">
              <AbdullahButton className="bg-red-500 text-white font-semibold">
                Delete my Account
              </AbdullahButton>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Page;