import { type AppType } from 'next/app';
import NextNProgress from 'nextjs-progressbar';
import { api } from '~/utils/api';
import 'react-toastify/dist/ReactToastify.css';
import '~/styles/globals.css';
import { Loading } from '~/components/common/Loading';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import 'reactflow/dist/style.css';
import 'react-loading-skeleton/dist/skeleton.css'
import { ReactFlowProvider } from 'reactflow';
import { AccessPopUp } from '~/components/common/AccessPopUp';



const MyApp: AppType = ({ Component, pageProps }) => {


  return (
    <div className="w-full h-fit relative">
      <NextNProgress options={{ showSpinner: false }} />
      <Loading />
      <AccessPopUp />
     
      <Head>
        <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
      </Head>
      <ReactFlowProvider>
        <Component {...pageProps} />
      </ReactFlowProvider>
    </div>
  );
};

export default api.withTRPC(MyApp);
