import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import logo from "~/assets/logo.png"
import hero from "~/assets/hero.png"
import { AbdullahButton } from "~/components/ui/buildingBlocks/AbdullahButton";


const Page: NextPage = () => {

  return (
    <>
      <Head>
        <title>openFlows</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async></script>
      </Head>
      <main className=" min-h-screen bg-gray-100 container mx-auto ">
        <nav className="w-full h-[70px] flex items-center justify-between p-4 ">
          <div className="w-[5%] h-full flex justify-start items-center  ">
          <Image src={logo}  alt ={"logo"} width={40} height={40}/>
          </div>
          <div className="w-[30%] h-full flex items-center justify-end gap-x-4 ">
           <AbdullahButton 
            className="!bg-gray-100 !text-orange-500 font-bold !rounded-3xl !text-md "
             onClick={() => console.log("hds")}  
             text="log in"
              title="log in a votre compte"
              />
           <AbdullahButton  className="!bg-orange-500 !text-white font-bold !rounded-3xl !text-md " onClick={() => console.log("hds")}  text=" sign up" title="log in a votre compte"/>
          </div>
        </nav>
        <div className="w-full custom-hieght-navbar flex justify-between px-4 ">
        <div className="text-start w-[50%] p-4  py-32 sm:py-28 lg:py-32  max-h-full ">
                  <h1 className="text-6xl  font-bold tracking-tight text-gray-900    ">
                     Gestion de projet <br />
                      Sonatrach R&D <br />
                     guidée par PMBOK <br />
                  </h1>

                  <p className="mt-6 text-md pt-8 leading-8 text-gray-900">
                     Découvrez la puissance de la gestion de projet guidée par PMBOK. Nos experts fournissent des résultats avec précision et confiance.
                     Découvrez la puissance de la gestion de projet guidée par PMBOK. Nos experts fournissent des résultats avec précision et confiance.
                  </p>
                 <div className="mt-10 flex items-center justify-start gap-x-6">
                    <a
                       href="#"
                       className="rounded-xl  px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm bg-gray-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                      >
                      commencer gratuitement <span aria-hidden="true">&rarr;</span>
                      </a>
                     
             
                  </div>
              </div>
              <div className="w-[50%] h-full  mt-8 max-h-full  ">
                 <Image

                   className="w-full  "
                    src={hero}
                   alt="hero-image"
                  />
      </div>


        </div>
      </main>
    </>
  );
};

export default Page;