import { type NextPage } from "next";
import Head from "next/head";
import { Hero } from "~/components/landing/Hero";
import { api } from "~/utils/api";
import NewLatter from "~/components/landing/NewLatter";
import { Pricing } from "~/components/landing/Pricing";
import { Creators } from "~/components/landing/Creators";


const Page: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
 console.log(hello?.data)
  return (
    <>
      <Head>
        <title>Alpha</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <script src="//code.tidio.co/f4ntqdkrkcmkov2pbgapiuevig4fhtbq.js" async></script>
      </Head>
      <main className=" min-h-screen bg-white ">
 
      <Hero />
    
      <Pricing />
      <Creators />
      <NewLatter />
  
      </main>
    </>
  );
};

export default Page;
