import { type NextPage } from "next";
import { Chain } from "~/components/common/Chain";
import { Header } from "~/components/common/Header";
import { useState , useEffect } from "react";
import { ProjectStarter } from "~/components/common/ProjectStarter";
import { api } from "~/utils/api";
import { toast } from "react-toastify";
import { loading_Reducer } from "~/store/app-reducer/loadingReducer";
import { userReducer } from "~/store/userReducer";
import setup from "~/assets/Starting a business project-rafiki.png"
import planning from "~/assets/Office management-rafiki.png"
import executing from "~/assets/horse jumping-cuate.png"
import controlling from "~/assets/Control Panel-rafiki.png"
import closing from "~/assets/Coronavirus Border Closure-amico.png"
import { getUserMetadata, setoreProjectMetaData, storeProjectCurrentPhaseAbdullah ,getProjectCurrentPhaseAbdullah } from "~/lib/MetaData";
import {  PAGES } from '~/store/app-reducer/headerReducer'
import { IsPhaseLocked } from "~/utils/access/IsPhaseLocked";
import Head from "next/head";
import BedgetStatus from "~/components/dashboard/BedgetStatus";
import Reminder from "~/components/dashboard/Reminder";
import Timer from "~/components/dashboard/Timer";

const Page: NextPage = () => {

  const [hasProjectStart , setHasProjectStart] = useState<boolean>(true)

  

  // const set_isLoading = loading_Reducer(state => state.set_isLoadingFully)
  const {refetch , isFetching} = api.ProjectRouter.getProjectStatus.useQuery({user_id : getUserMetadata() } , {
    onSuccess : (data) => {
        if(data.project_id){
          setHasProjectStart(true)
          setoreProjectMetaData({project_id : data.project_id as string} )
          storeProjectCurrentPhaseAbdullah(data.current_phase as string)
          return
        }
        setHasProjectStart(false)
        // set_isLoading({is_loading: false , fullWight:false})
      },
      onError : () => {
        toast("failed to get project status",{
          className:" !text-white !bg-blue-500",
          hideProgressBar: true,
         })
        //  set_isLoading({is_loading: false , fullWight:false})
      },

})

// useEffect(() => {
//   if(isFetching){
//     set_isLoading({is_loading: true , fullWight:true})
//   }else{
//     set_isLoading({is_loading: false , fullWight:false})
//   }
// } , [isFetching , set_isLoading])

  return (
    <>
       <Head>
        <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex flex-col overflow-x-hidden   w-full  items-center bg-gray-50 ">
         
          {
            
            hasProjectStart ?
            <div className=" mx-auto w-[85%]   p-4 ">
            <h1 className="text-gray-800  text-3xl text-start  my-4  " >Hi  abdullah 👋 this is the dashboard and your personal space</h1>
            {/* this is the first row */}
            <div className="w-full  mx-auto gap-x-8  rounded-lg  h-[200px] flex justify-center items-center my-4">
             <Reminder />
            
             
              <Timer />
            </div>
            {/* this is the second row */}
            <div className="w-full  mx-auto gap-x-8  rounded-lg  h-[400px] flex justify-center items-center my-4">
              <BedgetStatus />
              <div className="w-[40%]  bg-white rounded-lg h-[400px]">
              <h1>this is the second section</h1>
              </div>
            </div>
            {/* this is the thierd row */}
            <div className="my-4 w-full h-[70px] flex justify-start items-center ">
            <h1 className="text-gray-800  text-2xl text-start my-4  " >Contrôlez et configurez votre projet</h1>
            </div>
            <div className="w-full   mx-auto gap-x-8  rounded-lg min-h-[300px] h-fit flex justify-center items-center my-4">
              <Chain
               PAGE ={PAGES.STARTUP}
               available = {IsPhaseLocked({current_phase : getProjectCurrentPhaseAbdullah() , thisPhaseIndex : 0})}
               image={setup}
               path={`/app/startup`}
               name="Pre-démarrage" 
               selected />
             
           
              <Chain
                available = {IsPhaseLocked({current_phase : getProjectCurrentPhaseAbdullah() , thisPhaseIndex : 1})}
                PAGE ={PAGES.PLANNING}
                 
                image={planning}
                path={`/app/planning`} 
                name="Planification" 
              />
         

           
              <Chain 
                available = {IsPhaseLocked({current_phase : getProjectCurrentPhaseAbdullah() , thisPhaseIndex : 2})}
                PAGE ={PAGES.EXECUTING}
                  
                image={executing} 
                path={`/app/executing`}
                name="Exécution" 
               />
           
              <Chain 
                 available = {IsPhaseLocked({current_phase : getProjectCurrentPhaseAbdullah() , thisPhaseIndex : 3})}
                 PAGE ={PAGES.CONTROLLING}
                 image={controlling} 
                 path={`/app/controlling`}
                 name="Contrôler" />
        
            
              <Chain 
                 available = {IsPhaseLocked({current_phase : getProjectCurrentPhaseAbdullah() , thisPhaseIndex : 4})} 
                PAGE ={PAGES.CLOSING}
                image={closing} 
                path={`/app/close`} 
                name="Clôturer" />
          
            </div>
          </div>
            :
            <ProjectStarter refetch = {refetch} />
          }
     
      </main>
    </>
  );
};

export default Page;