import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Chain } from "~/components/common/Chain";
import { Header } from "~/components/common/Header";

import { api } from "~/utils/api";

const Page: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Alpha app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />

      </Head>
      <main className=" min-h-screen w-full bg-gray-50 ">
           <Header />
      <div className="container mx-auto">
        <h1 className="text-gray-800 font-bold text-2xl text-start ml-4 my-8  " >Contrôlez et configurez votre projet</h1>
        <div className="w-[80%] xl:w-[1060] mx-auto gap-x-8  rounded-lg min-h-[400px] h-fit flex justify-center items-center my-4">
          <Chain path={`/app/startup`} name="startup" />
          <Chain path={`/app/startup`} name="planning" />
          <Chain path={`/app/startup`} name="controlling" />
          <Chain path={`/app/startup`} name="executing" />
          <Chain path={`/app/startup`} name="close" />
            {/* <Chain /> */}
        {/* <div className='z-10 absolute  top-0 -left-4 w-80 h-80 bg-indigo-600 rounded-full mix-blend-multiply filter blur-xl opacity-25 animate-blob '  />
        <div className='z-10 absolute top-0 -right-4 w-80 h-80 bg-sky-400 rounded-full mix-blend-multiply filter blur-xl opacity-25  animate-Blob'  />
        <div className='z-10 absolute -bottom-8 -left-20 w-80 h-80 bg-pink-600 rounded-full mix-blend-multiply filter blur-xl opacity-25 animate-Blob'  /> */}
        </div>
      </div>
      </main>
    </>
  );
};

export default Page;