import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/common/Header";
import Upload from "~/components/common/Upload";
import { DocUi } from "~/components/ui/DocUi";
import { Sidebar } from "~/components/ui/Sidebar";




const Page: NextPage = () => {
  

  return (
    <>
      <Head>
      <title>Sonatrach</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
       <Sidebar />
       <div className="ml-[16rem] flex flex-col items-center  custom-width h-fit min-h-screen">
      
        <div className='w-full h-[50px] flex items-center justify-between  p-8 '>
           <div>
           <h1 className='font-bold text-gray-900 text-2xl '>👉startup/documents </h1>
           </div>
      <Upload />
       </div>
       <div className="w-full min-h-[200px] h-fit p-4 gap-4 flex flex-wrap ">
       {
        [1,2,3,4,5].map(item => <DocUi key={item}/>)
       }
       </div>
        
       </div>
     
      </main>
    </>
  );
};

export default Page;