import { type NextPage } from "next";
import Head from "next/head";

import { SideNav } from "~/components/common/SideNav";
import { Header } from "~/components/common/Header";
import { PageHeadComunication } from "~/components/planning/comunication/PageHeadComunication"; 




const Page: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>Sonatrach</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />

      </Head>
      <Header />
      <div className="   w-full  ">
     <SideNav />
     <main className="custopn-page-height-width bg-gray-100 h-full flex   ml-[7rem] ">
        <div className="w-[50%] p-4 h-full">
        <PageHeadComunication />
        </div>
        <div className="bg-black w-[50%] flex flex-col  h-full">
       
        </div>
 
     </main>
      </div>
    </>
  );
};

export default Page;