import { type NextPage } from "next";
import Head from "next/head";
import DescriptionIcon from "@mui/icons-material/Description";
import GroupIcon from "@mui/icons-material/Group";
import { TextEditor } from "~/components/planning/ui/TextEditor";




const Page: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>Sonatrach</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />

      </Head>
      <main className="  min-h-screen w-full bg-gray-50 ">
    
     
      <header className="flex justify-between items-center p-3 pb-1">
        <span  className="cursor-pointer">
          <DescriptionIcon
            className="text-blue-500"
            style={{ fontSize: "3rem" }}
          />
        </span>
        <div className="flex-grow px-2">
          <h2>file name</h2>
          <div
            className="flex items-center text-sm space-x-1 -ml-1 h-8
          text-gray-600"
          >
            <p className="option">File</p>
            <p className="option">Edit</p>
            <p className="option">View</p>
            <p className="option">Insert</p>
            <p className="option">Format</p>
            <p className="option">Tools</p>
          </div>
        </div>

        <button className="hidden md:inline-block w-32 px-6 py-2.5 bg-blue-700 text-white font-medium text-sm leading-tight rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-200 active:shadow-lg transition duration-150 ease-in-out">
          <GroupIcon className="text-white" /> SHARE
        </button>
       
      </header>
      <TextEditor />
    
      </main>
    </>
  );
};

export default Page;