import { type NextPage } from "next";
import Head from "next/head";
import DescriptionIcon from "@mui/icons-material/Description";
import GroupIcon from "@mui/icons-material/Group";
import { TextEditor } from "~/components/planning/ui/TextEditor";
import { SideNav } from "~/components/common/SideNav";
import { Header } from "~/components/common/Header";
import { PageHead } from "~/components/planning/ui/PageHead";




const Page: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>Sonatrach</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />

      </Head>
      <Header />
      <div className="   w-full  ">
     <SideNav />
     <main className="custopn-page-height-width bg-gray-100 h-full  ml-[7rem] p-4 ">
     <PageHead />
      
      <div className="bg-white h-[70%] flex justify-center p-4 rounded-lg w-[90%] mx-auto ">
      <TextEditor />
      </div>
     </main>
      </div>
    </>
  );
};

export default Page;