import { type NextPage } from "next";
import Head from "next/head";
import {  useState } from "react";
import { Header } from "~/components/header/Header";
import { PlanningSideBar } from "~/components/sideBars/PlanningSideBar";
import { AbdullahTable, type ItemTable } from "~/components/used/AbdullahTable";
import { Form } from "~/components/used/Form";
import { FormContainer } from "~/components/used/FormContainer";
import { RowGridText } from "~/components/typography/RowGridText";
import { TextField } from "~/components/used/TextField";






const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
 

 
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
      <PlanningSideBar setIsOpen ={setIsOpen} isOpen = {isOpen} />
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[0]"}`}>
     
      <Form >
      <div className="bg-white px-4 py-5 sm:p-6">
        <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
           <RowGridText text="Project management plan " />
           <RowGridText small text=" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt ex ad dicta animi soluta deleniti a distinctio quo. Non tempore numquam odio sequi iste adipisci laudantium aperiam, eius quas quidem." />
         
          <div className="col-span-6 lg:col-span-12 ">
             <AbdullahTable
                    isLoading={ false}
                    Action={false}
                    ActionName="Assign"
                    headers={["Phase" , "Key Deliverables" ]}
                    body={[]}
              />
           </div>
           <RowGridText text="Project Management Processes and Tailoring Decisions"/>
           {/* this is a row */}
           <TextField isLoading={false} lable="Integration Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Integration Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Scope Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Scope Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Time Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Time Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Cost Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Cost Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Quality Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Quality Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Human Resources Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Human Resources Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Communication Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Communication Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Risk Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Risk Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Procurement Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Procurement Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Stakeholders Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Stakeholders Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />

           <RowGridText text="Project Management Processes and Tailoring Decisions"/>
           {/* this is a row */}
           <TextField isLoading={false} lable="Integration Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Scope Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Time Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Cost Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Quality Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Human Resources Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Communication Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Risk Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Procurement Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Stakeholders Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           
           {/* get out of the sequance  */}
           <TextField isLoading={false} lable="Project Reviews" className="!col-span-12" onChange={(e) => console.log(e)} value={""} />
       </div>
    </div>
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;