import { type NextPage } from "next";
import Head from "next/head";
import {  useState } from "react";
import { toast } from "react-toastify";
import { Header } from "~/components/common/Header";
import { PlanningSideBar } from "~/components/sideBars/PlanningSideBar";
import { AssignTaskPopUp } from "~/components/ui/plusTable/executing/AssignTaskPopUp";
import { StakeHolder } from "~/components/ui/popup/StakeHolder";
import { AbdullahTable, type ItemTable } from "~/components/ui/used/AbdullahTable";
import { Form } from "~/components/ui/used/Form";
import { FormContainer } from "~/components/ui/used/FormContainer";
import { FormHead } from "~/components/ui/used/FormHead";
import { RowGridText } from "~/components/ui/used/RowGridText";
import { TextField } from "~/components/ui/used/TextField";
import { getProjectMetaData } from "~/lib/MetaData";
import { loading_Reducer } from "~/store/app-reducer/loadingReducer";
import type { task } from "~/types/type";
import { api } from "~/utils/api";

type stekholder ={
  id : string ,
  name : string
}


const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
  const [tasks , setTasks ] = useState<task[]>([])
  const [stakholders , setStakHolders ] = useState<stekholder[]>([])
  const set_loading = loading_Reducer(state => state.set_isLoading)

  // get all the tasks 
  const tasksGet = api.tasksRouter.getAllTasks.useQuery({project_id : getProjectMetaData()},{
    onSuccess(data) {
      setTasks(data as task[])
    
    
      set_loading(false)
    },
    onError(err) {
      console.log(err)
      toast("error fetching the tasks  ",{
        className:" !text-white !bg-blue-500",
        hideProgressBar: true,
       })
       set_loading(false)
       },
  })

  const { isFetching } = api.stakHolderRouter.getAllStackHolders.useQuery({project_id : getProjectMetaData()} , {
    onSuccess(data) {
      setStakHolders(data as stekholder[])
      set_loading(false)
    },
    onError(){
      toast("failed to get the stakholders",{
        className:" !text-white !bg-blue-500",
        hideProgressBar: true,
       })
       set_loading(false)
     
    },
  })


 

  // prepare the items to be handled by the table
  // AssignTaskPopUp
  const satisfieTable = () : ItemTable[] => {
    const array : ItemTable[] =  tasks.map(item => {

      const involvedStackHolders = item?.assign_to

      const assignedTo : stekholder[] = []
      involvedStackHolders?.forEach(current => {
        const up : stekholder[]   = stakholders.filter(stakholder => stakholder.id === current)
       if( up &&  up.length > 0  )  {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        assignedTo.push(up[0]!)
       }
      })
      return  {
        id : item.id ,
        callback : (id : string) => console.log(id),
        properties : [item.name , assignedTo.map(pro => (
          <StakeHolder id ={pro.id}  key={pro.id} text={pro.name} />
        )) , <AssignTaskPopUp refetch={tasksGet.refetch} taskName={item.name} id={item.id} key={item.id} />]
      } 
    })
    return array
  }
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
      <PlanningSideBar setIsOpen ={setIsOpen} isOpen = {isOpen} />
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[0]"}`}>
     
      <Form >
      <div className="bg-white px-4 py-5 sm:p-6">
        <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
           <RowGridText text="Project management plan " />
           <RowGridText small text=" Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt ex ad dicta animi soluta deleniti a distinctio quo. Non tempore numquam odio sequi iste adipisci laudantium aperiam, eius quas quidem." />
         
          <div className="col-span-6 lg:col-span-12 ">
             <AbdullahTable
                    isLoading={ false}
                    Action={false}
                    ActionName="Assign"
                    headers={["Phase" , "Key Deliverables" ]}
                    body={satisfieTable()}
              />
           </div>
           <RowGridText text="Project Management Processes and Tailoring Decisions"/>
           {/* this is a row */}
           <TextField isLoading={false} lable="Integration Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Integration Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Scope Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Scope Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Time Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Time Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Cost Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Cost Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Quality Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Quality Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Human Resources Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Human Resources Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Communication Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Communication Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Risk Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Risk Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Procurement Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Procurement Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Stakeholders Processes" onChange={(e) => console.log(e)} value={""} />
           <TextField isLoading={false} lable="Stakeholders Tailoring Decisions" onChange={(e) => console.log(e)}  value={""} />

           <RowGridText text="Project Management Processes and Tailoring Decisions"/>
           {/* this is a row */}
           <TextField isLoading={false} lable="Integration Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Scope Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Time Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Cost Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Quality Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Human Resources Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Communication Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Risk Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Procurement Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           {/* this is a row */}
           <TextField isLoading={false} lable="Stakeholders Tools and Techniques" onChange={(e) => console.log(e)} value={""} />
           
           {/* get out of the sequance  */}
           <TextField isLoading={false} lable="Project Reviews" className="!col-span-12" onChange={(e) => console.log(e)} value={""} />
       </div>
    </div>
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;