import { type NextPage } from "next";
import Head from "next/head";
import {  useState } from "react";
import { Header } from "~/components/common/Header";
import { FolderIcon } from "@heroicons/react/20/solid";
import FileDocs from "~/components/docsComponents/file";


const LISTA = [
  {
    name : "start up " , 
    path : "/app/startup"
  },
  {
    name : "planning " , 
    path : "/app/startup"
  },
  {
    name : "executing" , 
    path : "/app/startup"
  },
  {
    name : "controlling" , 
    path : "/app/startup"
  },
  {
    name : "closing" , 
    path : "/app/startup"
  },
]


const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
 
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full justify-center items-center bg-gray-50 ">
      <div className="w-[80%] h-[80%] rounded-lg flex gap-x-4 bg-white shadow-lg  flex-col ">
        <div className="w-full h-[70px] flex justify-start items-center pl-4">
                <button>
                    return 
                </button>
        </div>
        <div className="w-full min-h-[300px] h-full flex gap-x-4 p-8 ">
        <FileDocs isDocument= {false} text="project charter" />
        <FileDocs isDocument= {false} text="bla bla" />
        </div>
      </div>
      </main>
    </>
  );
};

export default Page;